name = "Lvs Studio"
studio_window_name = "Lvs Studio"
app_window_name = "Unnamed"
creator_name = "Viktor Shulgovsky"
company_name = "Viktor Shulgovsky"
year = 2026
version = "4.0.0"
logo_png = "Logo/LogoShape.png"
logo_ico = "Logo/LogoShape.ico"
product_name_studio = "Lvs Studio"
product_name_app = "Lvs App"
credits = [
  "famfamfam-silk icon pack by Mark James (https://github.com/markjames/famfamfam-silk-icons)",
  "STB public domain libraries by Sean Barrett",
]