if(NOT DEFINED SOURCE_DIR OR NOT DEFINED DEST_DIR)
    message(FATAL_ERROR "SOURCE_DIR and DEST_DIR are required")
endif()

if(NOT EXISTS "${SOURCE_DIR}")
    message(FATAL_ERROR "Content source directory not found: ${SOURCE_DIR}")
endif()

file(REMOVE_RECURSE "${DEST_DIR}")
file(MAKE_DIRECTORY "${DEST_DIR}")

file(GLOB_RECURSE content_files LIST_DIRECTORIES false "${SOURCE_DIR}/*")
foreach(src_file IN LISTS content_files)
    string(REPLACE "\\" "/" src_file_norm "${src_file}")
    string(REGEX MATCH "\\.md$" is_markdown "${src_file_norm}")
    if(is_markdown)
        continue()
    endif()
    string(REGEX MATCH "\\.(vert|frag|geom|tesc|tese|comp)$" is_shader_source "${src_file_norm}")
    if(is_shader_source)
        continue()
    endif()
    string(REGEX MATCH "\\.glsl$" is_glsl "${src_file_norm}")
    string(REGEX MATCH "/CompiledShaders/" is_compiled_shader "${src_file_norm}")
    if(is_compiled_shader)
        string(REGEX MATCH "\\.(spv|glsl)$" is_compiled_output "${src_file_norm}")
        if(NOT is_compiled_output)
            continue()
        endif()
    endif()
    if(is_glsl AND NOT is_compiled_shader)
        continue()
    endif()

    file(RELATIVE_PATH rel_path "${SOURCE_DIR}" "${src_file}")
    set(dst_file "${DEST_DIR}/${rel_path}")
    get_filename_component(dst_dir "${dst_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${dst_dir}")
    file(COPY "${src_file}" DESTINATION "${dst_dir}")
endforeach()
