file(GLOB_RECURSE LVS_ENGINE_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Engine/*.cpp"
)
file(GLOB_RECURSE LVS_ENGINE_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Engine/*.hpp"
)

file(GLOB_RECURSE LVS_QT_COMMON_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Qt/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/AppInfo.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Launcher/*.cpp"
)
file(GLOB_RECURSE LVS_QT_COMMON_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Qt/*.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/AppInfo.hpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Launcher/*.hpp"
)

file(GLOB_RECURSE LVS_APP_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/App/*.cpp"
)
file(GLOB_RECURSE LVS_APP_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/App/*.hpp"
)

file(GLOB_RECURSE LVS_STUDIO_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Studio/*.cpp"
)
file(GLOB_RECURSE LVS_STUDIO_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/Lvs/Studio/*.hpp"
)
