function(lvs_apply_windows_resources target)
    if(NOT WIN32)
        return()
    endif()

    set(app_info_toml "${CMAKE_CURRENT_SOURCE_DIR}/config/AppInfo.toml")
    if(NOT EXISTS "${app_info_toml}")
        message(FATAL_ERROR "App info file not found: ${app_info_toml}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${app_info_toml}")

    function(_lvs_toml_get_string out key)
        file(STRINGS "${app_info_toml}" _lines REGEX "^[ \t]*${key}[ \t]*=" LIMIT_COUNT 1)
        if(NOT _lines)
            set(${out} "" PARENT_SCOPE)
            return()
        endif()
        list(GET _lines 0 _line)
        string(REGEX MATCH "^[ \t]*${key}[ \t]*=[ \t]*\"([^\"]*)\"" _m "${_line}")
        if(CMAKE_MATCH_1)
            set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
        else()
            set(${out} "" PARENT_SCOPE)
        endif()
    endfunction()

    function(_lvs_toml_get_int out key)
        file(STRINGS "${app_info_toml}" _lines REGEX "^[ \t]*${key}[ \t]*=" LIMIT_COUNT 1)
        if(NOT _lines)
            set(${out} "0" PARENT_SCOPE)
            return()
        endif()
        list(GET _lines 0 _line)
        string(REGEX MATCH "^[ \t]*${key}[ \t]*=[ \t]*([0-9]+)" _m "${_line}")
        if(CMAKE_MATCH_1)
            set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
        else()
            set(${out} "0" PARENT_SCOPE)
        endif()
    endfunction()

    _lvs_toml_get_string(icon_rel "logo_ico")
    _lvs_toml_get_string(company_name "company_name")
    _lvs_toml_get_string(product_version "version")
    _lvs_toml_get_int(year "year")
    _lvs_toml_get_string(product_name_studio "product_name_studio")
    _lvs_toml_get_string(product_name_app "product_name_app")

    if(icon_rel STREQUAL "")
        set(icon_rel "Logo/LogoShape.ico")
    endif()
    if(company_name STREQUAL "")
        set(company_name "Unknown")
    endif()
    if(product_version STREQUAL "")
        set(product_version "0.0.0")
    endif()
    if(year STREQUAL "0")
        set(year "2026")
    endif()

    if(target STREQUAL "lvs_studio")
        set(file_description "${product_name_studio}")
    elseif(target STREQUAL "lvs_app")
        set(file_description "${product_name_app}")
    else()
        set(file_description "${target}")
    endif()

    set(icon_path "${CMAKE_CURRENT_SOURCE_DIR}/content/${icon_rel}")
    if(NOT EXISTS "${icon_path}")
        message(FATAL_ERROR "Windows icon file not found: ${icon_path}")
    endif()

    set(rc_out "${CMAKE_CURRENT_BINARY_DIR}/${target}_version.rc")
    set(version_numeric "${product_version}")
    string(REPLACE "." ";" version_parts "${version_numeric}")
    list(LENGTH version_parts version_count)
    while(version_count LESS 4)
        list(APPEND version_parts "0")
        list(LENGTH version_parts version_count)
    endwhile()
    list(GET version_parts 0 v0)
    list(GET version_parts 1 v1)
    list(GET version_parts 2 v2)
    list(GET version_parts 3 v3)
    set(file_version_comma "${v0},${v1},${v2},${v3}")
    set(product_version_comma "${v0},${v1},${v2},${v3}")
    set(original_filename "${target}.exe")
    set(internal_name "${target}")
    set(product_name "${file_description}")
    set(legal_copyright "Copyright (C) ${year} ${company_name}")
    configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/cmake/resources/version.rc.in"
        "${rc_out}"
        @ONLY
    )

    target_sources(${target} PRIVATE "${rc_out}")
endfunction()
